<?php

namespace Container8X8txj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateAdministratorCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateAdministratorCommand' shared autowired service.
     *
     * @return \App\Command\CreateAdministratorCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CreateAdministratorCommand.php';

        $instance = new \App\Command\CreateAdministratorCommand(($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:create-administrator');
        $instance->setDescription('Creation compte Adminsitrateur');

        return $container->privates['App\\Command\\CreateAdministratorCommand'] = $instance;
    }
}
