<?php

namespace Container8X8txj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIntraControlleremailSimpleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6oz77xL.App\Service\IntraController::emailSimple()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.6oz77xL.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.6oz77xL": it needs an instance of "App\\Entity\\User" but this type has been excluded because it\'s a Doctrine entity.'],
            'messageBus' => ['services', 'messenger.default_bus', 'getMessenger_DefaultBusService', false],
        ], [
            'user' => 'App\\Entity\\User',
            'messageBus' => '?',
        ]))->withContext('App\\Service\\IntraController::emailSimple()', $container);

        if (isset($container->privates['.service_locator.6oz77xL.App\\Service\\IntraController::emailSimple()'])) {
            return $container->privates['.service_locator.6oz77xL.App\\Service\\IntraController::emailSimple()'];
        }

        return $container->privates['.service_locator.6oz77xL.App\\Service\\IntraController::emailSimple()'] = $instance;
    }
}
