<?php

namespace Container8X8txj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIntraControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\IntraController' shared autowired service.
     *
     * @return \App\Service\IntraController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/IntraController.php';

        try {
            $instance = new \App\Service\IntraController();

            if (isset($container->services['App\\Service\\IntraController'])) {
                return $container->services['App\\Service\\IntraController'];
            }

            $container->services['App\\Service\\IntraController'] = $instance;

            $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Service\\IntraController', $container));

            return $instance;
        } catch (\Throwable $e) {
            unset($container->services['App\\Service\\IntraController']);

            throw $e;
        }
    }
}
