<?php

namespace Container8X8txj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationControllerverifyUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T__ygNF.App\Controller\RegistrationController::verifyUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'jwtService' => ['privates', 'App\\Service\\JwtService', 'getJwtServiceService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'jwtService' => 'App\\Service\\JwtService',
            'userRepository' => 'App\\Repository\\UserRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\RegistrationController::verifyUser()', $container);

        if (isset($container->privates['.service_locator.T__ygNF.App\\Controller\\RegistrationController::verifyUser()'])) {
            return $container->privates['.service_locator.T__ygNF.App\\Controller\\RegistrationController::verifyUser()'];
        }

        return $container->privates['.service_locator.T__ygNF.App\\Controller\\RegistrationController::verifyUser()'] = $instance;
    }
}
