<?php

namespace ContainerQuiL2jp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U1Xt0auService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.U1Xt0au' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\MainController::index' => ['privates', '.service_locator.PTOAT3f.App\\Controller\\MainController::index()', 'getMainControllerindexService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.TcpiOa7.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController::verifyUser' => ['privates', '.service_locator.T__ygNF.App\\Controller\\RegistrationController::verifyUser()', 'getRegistrationControllerverifyUserService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Service\\IntraController::emailValidate' => ['privates', '.service_locator.nsvnigb.App\\Service\\IntraController::emailValidate()', 'getIntraControlleremailValidateService', true],
            'App\\Service\\IntraController::emailSimple' => ['privates', '.service_locator.6oz77xL.App\\Service\\IntraController::emailSimple()', 'getIntraControlleremailSimpleService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\MainController:index' => ['privates', '.service_locator.PTOAT3f.App\\Controller\\MainController::index()', 'getMainControllerindexService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.TcpiOa7.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController:verifyUser' => ['privates', '.service_locator.T__ygNF.App\\Controller\\RegistrationController::verifyUser()', 'getRegistrationControllerverifyUserService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Service\\IntraController:emailValidate' => ['privates', '.service_locator.nsvnigb.App\\Service\\IntraController::emailValidate()', 'getIntraControlleremailValidateService', true],
            'App\\Service\\IntraController:emailSimple' => ['privates', '.service_locator.6oz77xL.App\\Service\\IntraController::emailSimple()', 'getIntraControlleremailSimpleService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\MainController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUser' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Service\\IntraController::emailValidate' => '?',
            'App\\Service\\IntraController::emailSimple' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\MainController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUser' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Service\\IntraController:emailValidate' => '?',
            'App\\Service\\IntraController:emailSimple' => '?',
        ]);

        if (isset($container->privates['.service_locator.U1Xt0au'])) {
            return $container->privates['.service_locator.U1Xt0au'];
        }

        return $container->privates['.service_locator.U1Xt0au'] = $instance;
    }
}
