<?php

namespace ContainerQuiL2jp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_67VWtkDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.67VWtkD' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/MessageHandler/SendActivationMessageHandler.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['.messenger.handler_descriptor.67VWtkD'])) {
            return $container->privates['.messenger.handler_descriptor.67VWtkD'];
        }

        $instance = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\MessageHandler\SendActivationMessageHandler($a), []);

        if (isset($container->privates['.messenger.handler_descriptor.67VWtkD'])) {
            return $container->privates['.messenger.handler_descriptor.67VWtkD'];
        }

        return $container->privates['.messenger.handler_descriptor.67VWtkD'] = $instance;
    }
}
