<?php

namespace ContainerQuiL2jp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateAuthorCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateAuthorCommand' shared autowired service.
     *
     * @return \App\Command\CreateAuthorCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CreateAuthorCommand.php';

        $instance = new \App\Command\CreateAuthorCommand(($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:create-author');
        $instance->setDescription('Creation compte Auteur');

        return $container->privates['App\\Command\\CreateAuthorCommand'] = $instance;
    }
}
