<?php

namespace ContainerQuiL2jp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateAdministratorCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CreateAdministratorCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CreateAdministratorCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-administrator', [], 'Creation compte Adminsitrateur', false, #[\Closure(name: 'App\\Command\\CreateAdministratorCommand')] fn (): \App\Command\CreateAdministratorCommand => ($container->privates['App\\Command\\CreateAdministratorCommand'] ?? $container->load('getCreateAdministratorCommandService')));
    }
}
