<?php

namespace ContainerQuiL2jp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIntraControlleremailValidateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nsvnigb.App\Service\IntraController::emailValidate()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.nsvnigb.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.nsvnigb": it needs an instance of "App\\Entity\\User" but this type has been excluded because it\'s a Doctrine entity.'],
            'jwt' => ['privates', 'App\\Service\\JwtService', 'getJwtServiceService', true],
            'messageBus' => ['services', 'messenger.default_bus', 'getMessenger_DefaultBusService', false],
        ], [
            'user' => 'App\\Entity\\User',
            'jwt' => 'App\\Service\\JwtService',
            'messageBus' => '?',
        ]))->withContext('App\\Service\\IntraController::emailValidate()', $container);

        if (isset($container->privates['.service_locator.nsvnigb.App\\Service\\IntraController::emailValidate()'])) {
            return $container->privates['.service_locator.nsvnigb.App\\Service\\IntraController::emailValidate()'];
        }

        return $container->privates['.service_locator.nsvnigb.App\\Service\\IntraController::emailValidate()'] = $instance;
    }
}
