<?php

namespace ContainerQuiL2jp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMainControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PTOAT3f.App\Controller\MainController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'session' => ['privates', '.errored..service_locator.PTOAT3f.Symfony\\Component\\HttpFoundation\\Session\\Session', NULL, 'Cannot autowire service ".service_locator.PTOAT3f": it references class "Symfony\\Component\\HttpFoundation\\Session\\Session" but no such service exists.'],
            'intraController' => ['services', 'App\\Service\\IntraController', 'getIntraControllerService', true],
            'jwtService' => ['privates', 'App\\Service\\JwtService', 'getJwtServiceService', true],
            'messageBus' => ['services', 'messenger.default_bus', 'getMessenger_DefaultBusService', false],
        ], [
            'session' => 'Symfony\\Component\\HttpFoundation\\Session\\Session',
            'intraController' => 'App\\Service\\IntraController',
            'jwtService' => 'App\\Service\\JwtService',
            'messageBus' => '?',
        ]))->withContext('App\\Controller\\MainController::index()', $container);

        if (isset($container->privates['.service_locator.PTOAT3f.App\\Controller\\MainController::index()'])) {
            return $container->privates['.service_locator.PTOAT3f.App\\Controller\\MainController::index()'];
        }

        return $container->privates['.service_locator.PTOAT3f.App\\Controller\\MainController::index()'] = $instance;
    }
}
