<?php

namespace ContainerQuiL2jp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationControllerregisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TcpiOa7.App\Controller\RegistrationController::register()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userPasswordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
            'intraController' => ['services', 'App\\Service\\IntraController', 'getIntraControllerService', true],
            'jwtService' => ['privates', 'App\\Service\\JwtService', 'getJwtServiceService', true],
            'messageBus' => ['services', 'messenger.default_bus', 'getMessenger_DefaultBusService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'userPasswordHasher' => '?',
            'entityManager' => '?',
            'validator' => '?',
            'intraController' => 'App\\Service\\IntraController',
            'jwtService' => 'App\\Service\\JwtService',
            'messageBus' => '?',
            'security' => '?',
        ]))->withContext('App\\Controller\\RegistrationController::register()', $container);

        if (isset($container->privates['.service_locator.TcpiOa7.App\\Controller\\RegistrationController::register()'])) {
            return $container->privates['.service_locator.TcpiOa7.App\\Controller\\RegistrationController::register()'];
        }

        return $container->privates['.service_locator.TcpiOa7.App\\Controller\\RegistrationController::register()'] = $instance;
    }
}
